customer_name=input("Enter the name:")
cust_id=input("enter the id:")
phone_no=input("enter phone no:")
total_items_purchased=input("enter total items:")
price_of_items=input("the price of items=")
print("name:",customer_name)
print("cust_id:",cust_id)
print("phone no:",phone_no)
print("total items:",total_items_purchased)
print("price:",price_of_items)