customer_name=input("Enter the name:")
cust_id=input("enter the id:")
phone_no=input("enter phone no:")
total_items_purchased=input("enter total items:")
price_of_items=input("the price of items=")
print("\t",customer_name,"\t",cust_id,"\t",phone_no,"\t",total_items_purchased,"\t",price_of_items)
